"""
PDB (Protein Data Bank) format support.

Basic support for reading and writing PDB format files. This is a simplified
implementation focused on coordinate data, not full PDB specification.
"""

from pathlib import Path
from typing import Optional, Union
import re
import numpy as np

from ..core import Molecule, Crystal, Lattice


def read_PDB(filename: str, as_crystal: bool = False) -> Union[Molecule, Crystal]:
    """
    Read a PDB format file.

    PDB format is primarily for proteins/molecules, but can also represent
    crystal structures. By default, returns a Molecule.

    Args:
        filename: Path to the PDB file
        as_crystal: If True, return Crystal (requires CRYST1 record)

    Returns:
        Molecule or Crystal: Structure from the file

    Raises:
        FileNotFoundError: If file doesn't exist
        ValueError: If file format is invalid
    """
    filepath = Path(filename)
    if not filepath.exists():
        raise FileNotFoundError(f"PDB file not found: {filename}")

    with open(filepath, "r") as f:
        lines = f.readlines()

    # Parse CRYST1 record if present (for crystal structures)
    lattice = None
    for line in lines:
        if line.startswith("CRYST1"):
            # Format: CRYST1   a     b     c    alpha  beta gamma spacegroup
            try:
                a = float(line[6:15])
                b = float(line[15:24])
                c = float(line[24:33])
                alpha = float(line[33:40])
                beta = float(line[40:47])
                gamma = float(line[47:54])
                lattice = Lattice.from_parameters(a, b, c, alpha, beta, gamma)
                break
            except (ValueError, IndexError):
                pass

    # Parse ATOM and HETATM records
    species = []
    positions = []

    for line in lines:
        if line.startswith(("ATOM  ", "HETATM")):
            try:
                # Extract element (columns 76-77, or infer from atom name)
                atom_name = line[12:16].strip()
                # Try to get element from columns 76-77
                if len(line) > 77:
                    element = line[76:78].strip()
                else:
                    cleaned = atom_name.strip()
                    base = re.sub(r'[0-9+\-]', '', cleaned)
                    if len(base) >= 2:
                        two_letter = base[:2].upper()
                        if two_letter[0].isalpha() and two_letter[1].islower():
                            element = two_letter
                        else:
                            element = base[0].upper() if base and base[0].isalpha() else "X"
                    elif base and base[0].isalpha():
                        element = base[0].upper()
                    else:
                        element = "X"

                # Extract coordinates
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])

                species.append(element)
                positions.append([x, y, z])
            except (ValueError, IndexError) as e:
                raise ValueError(f"Malformed PDB ATOM/HETATM line: {line.strip()}")

    if not species:
        raise ValueError("No valid ATOM or HETATM records found in PDB file")

    if as_crystal:
        if lattice is None:
            raise ValueError("as_crystal=True requires a valid CRYST1 record")
        # Convert to fractional coordinates
        frac_positions = []
        for pos in positions:
            cart_pos = np.array(pos)
            frac_pos = np.dot(cart_pos, lattice.inv_matrix)
            frac_positions.append(frac_pos.tolist())
        return Crystal(species, frac_positions, lattice, coords_are_cartesian=False)
    else:
        return Molecule(species, positions)


def write_PDB(
    structure: Union[Molecule, Crystal], filename: str, title: Optional[str] = None
) -> None:
    """
    Write a structure to a PDB format file.

    Args:
        structure: Molecule or Crystal object to write
        filename: Output filename
        title: Optional title/header (default: structure formula)

    Raises:
        ValueError: If structure is not a valid Molecule or Crystal
    """
    if not isinstance(structure, (Molecule, Crystal)):
        raise ValueError("write_PDB requires a Molecule or Crystal object")

    if title is None:
        title = (
            structure.formula if hasattr(structure, "formula") else "MatSimPy Structure"
        )

    filepath = Path(filename)

    with open(filepath, "w") as f:
        # Write header
        f.write(f"HEADER    {title[:40]:<40s}\n")
        f.write("REMARK   1 Generated by MatSimPy\n")

        # Write CRYST1 record if Crystal
        if isinstance(structure, Crystal):
            f.write(
                "CRYST1{:9.3f}{:9.3f}{:9.3f}{:7.2f}{:7.2f}{:7.2f} P 1           1\n".format(
                    structure.lattice.a,
                    structure.lattice.b,
                    structure.lattice.c,
                    structure.lattice.alpha,
                    structure.lattice.beta,
                    structure.lattice.gamma,
                )
            )
            # Use fractional positions converted to cartesian
            positions = structure.cart_positions
        else:
            positions = structure.positions

        # Write ATOM records
        for i, (specie, pos) in enumerate(zip(structure.species, positions)):
            atom_num = i + 1
            atom_name = f"{specie:>2s}"
            res_name = "UNK"
            res_num = 1
            chain = "A"

            # Format: ATOM  serial  name alt res chain resseq x y z occ temp element
            f.write(
                "ATOM  {:5d} {:>4s} {:1s}{:3s} {:1s}{:4d}    {:8.3f}{:8.3f}{:8.3f}{:6.2f}{:6.2f}          {:>2s}\n".format(
                    atom_num,
                    atom_name,
                    " ",  # alt location
                    res_name,
                    chain,
                    res_num,
                    pos[0],
                    pos[1],
                    pos[2],
                    1.0,  # occupancy
                    0.0,  # temp factor
                    specie,
                )
            )

        f.write("END\n")


__all__ = ["read_PDB", "write_PDB"]

# --- Registry registration ---
from .registry import registry, FormatHandler

_PDB_HANDLER = FormatHandler(
    name="pdb",
    extensions=(".pdb",),
    aliases=("pdb", "PDB"),
    description="Protein Data Bank format",
    reader=read_PDB,
    writer=write_PDB,
    supports_crystal=True,
    supports_molecule=True,
    strict_by_default=True,
)
registry.register(_PDB_HANDLER)
